name: Tests on Linux

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Run unit tests
      run: go test -race -vet=off ./...

    - name: Build command util
      run: go build

    - name: Install dependencies for command utility.
      run: sudo apt update -y && sudo apt install -y ssh

    - name: Run integration tests for command utility.
      run: ./tests.sh
